##
# Open Space Program
# Copyright © 2019-2020 Open Space Program Project
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##

[vehicle_pitch_up]
primary = "S"
secondary = "None"

[vehicle_pitch_dn]
primary = "W"
secondary = "None"

[vehicle_yaw_lf]
primary = "A"
secondary = "None"

[vehicle_yaw_rt]
primary = "D"
secondary = "None"

[vehicle_roll_lf]
primary = "Q"
secondary = "None"

[vehicle_roll_rt]
primary = "E"
secondary = "None"

[vehicle_thr_max]
primary = "Z"
secondary = "None"

[vehicle_thr_min]
primary = "X"
secondary = "None"

[vehicle_self_destruct]
primary = "LCtrl+C"
secondary = "LShift+A"

[game_switch]
primary = "V"
secondary = "None"

[ui_up]
primary = "Up"
secondary = "None"

[ui_dn]
primary = "Down"
secondary = "None"

[ui_lf]
primary = "Left"
secondary = "None"

[ui_rt]
primary = "Right"
secondary = "None"

[ui_rmb]
primary = "RtMouse"
secondary = "None"