/**
 * Open Space Program
 * Copyright © 2019-2020 Open Space Program Project
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#pragma once

#include "activetypes.h"
#include "../types.h"

#include <Corrade/Containers/ArrayView.h>
#include <entt/core/family.hpp>

#include <functional>
#include <unordered_map>

namespace osp::active
{
    struct EntityToDraw;
}

// Minor optimization:
// Set storage traits for RenderGroup::Storage_t to not use signals. This is
// also used by entt::view
template<>
struct entt::storage_traits<osp::active::ActiveEnt, osp::active::EntityToDraw>
{
    using storage_type = basic_storage<osp::active::ActiveEnt, osp::active::EntityToDraw>;
};

//-----------------------------------------------------------------------------

namespace osp::active
{

using material_family_t = entt::family<struct material_type>;
using material_id_t = material_family_t::family_type;

struct MaterialCommon { };
struct MaterialTerrain { };
struct MaterialSkybox { };

struct ACompMaterial
{
    material_id_t m_type;
};

//-----------------------------------------------------------------------------

/**
 * @brief Stores a draw function and user data needed to draw a single entity
 *
 * This is usually generated by a DrawAssigner_t
 */
struct EntityToDraw
{
    /**
     * @brief A function pointer to a Shader's draw() function
     *
     * @param ActiveEnt    [in] The entity being drawn; used to fetch component data
     * @param ActiveScene& [ref] The scene containing the entity's component data
     * @param ACompCamera  [in] Camera used to draw the scene
     * @param void*        [in] User data
     */
    using ShaderDrawFnc_t = void (*)(
            ActiveEnt, ActiveScene&, ACompCamera const&, void*) noexcept;

    constexpr void operator()(
            ActiveEnt ent, ActiveScene& rScene,
            ACompCamera const& camera) const noexcept
    {
        m_draw(ent, rScene, camera, m_data);
    }

    ShaderDrawFnc_t m_draw;
    // Non-owning user data passed to draw function, such as the shader
    void *m_data;

}; // struct EntityToDraw

/**
 * @brief Tracks a set of entities and their assigned drawing functions
 *
 * Each new entity added (in ACtxRenderGroups::m_added) is passed to one of
 * every RenderGroup's DrawAssigner_t depending on its material type, which is
 * responsible for setting its draw function and shader.
 *
 * DrawAssigners allow each RenderGroup to assign their own shaders for each
 * kind of material. RenderGroups are intended to be associated with certain
 * rendering techniques like Forward, Deferred, and Shadow mapping.
 *
 * This also works with game-specific modes like Thermal Imaging.
 */
struct RenderGroup
{
    using Storage_t = entt::storage_traits<ActiveEnt, EntityToDraw>::storage_type;
    using ArrayView_t = Corrade::Containers::ArrayView<ActiveEnt>;

    /**
     * @brief Assigns drawing functions and user data (like shaders) to entities
     *        of a certain material type for each RenderGroup
     *
     * @param ActiveScene& [ref] Scene the entities are part of
     * @param Storage_t&   [ref] Storage to add accepted entities and data to
     * @param ArrayView_t  [in] Entities to consider
     */
    using DrawAssigner_t = std::function<
            void(ActiveScene&, Storage_t&, ArrayView_t) >;

    /**
     * @brief Set the DrawAssigner function for a certain material type
     */
    template<typename MATERIAL_T>
    void set_assigner(DrawAssigner_t assigner)
    {
        material_id_t id = material_family_t::type<MATERIAL_T>;
        m_assigners.resize(std::max(m_assigners.size(), size_t(id + 1)));
        m_assigners[id] = std::move(assigner);
    }

    /**
     * @return Iterable view for stored entities
     */
    decltype(auto) view()
    {
        return entt::basic_view{m_entities};
    }

    /**
     * @return Iterable view for stored entities
     */
    decltype(auto) view() const
    {
        return entt::basic_view{m_entities};
    }

    // index with material_id_t
    std::vector<DrawAssigner_t> m_assigners;
    Storage_t m_entities;

}; // struct RenderGroup

/**
 * @brief Stores RenderGroups in the scene
 */
struct ACtxRenderGroups
{
    ACtxRenderGroups() = default;
    ACtxRenderGroups(ACtxRenderGroups const&) = delete;

    /**
     * @brief Resize vectors to fit all specified material IDs
     */
    template<typename ... MATERIAL_T>
    void resize_to_fit()
    {
        size_t minSize{std::max({material_family_t::type<MATERIAL_T> ...}) + 1};

        m_added.resize(minSize);
    }

    /**
     * @brief Adds a single entity to be considered by RenderGroups and
     *        assigned draw functions
     *
     * @tparam MATERIAL_T Material of newly added entity
     */
    template<typename MATERIAL_T>
    void add(ActiveEnt ent)
    {
        m_added[material_family_t::type<MATERIAL_T>].push_back(ent);
    }

    std::unordered_map< std::string, RenderGroup > m_groups;

    // access with m_added[materialID]
    std::vector< std::vector<ActiveEnt> > m_added;

}; // struct ACtxRenderGroups

//-----------------------------------------------------------------------------

/**
 * @brief Represents an entity which requests the scene to be drawn to m_target
 */
struct ACompRenderingAgent
{
    ActiveEnt m_target;  // Must have ACompRenderTarget
};

/**
 * @brief Describes the type of view used by a rendering agent
 */
struct ACompPerspective3DView
{
    ActiveEnt m_camera;
};

/**
 * @brief An object that is completely opaque
 */
struct ACompOpaque {};

/**
 *  @brief An object with transparency
 */
struct ACompTransparent {};

/**
 * @brief Visibility state of this object
 */
struct ACompVisible {};

/**
 * @brief World transform used for rendering.
 *
 * All ascendents of an entity using this must also have this component
 */
struct ACompDrawTransform
{
    Matrix4 m_transformWorld;
};

} // namespace osp::active

