name: Windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Install dependencies
      run: |
        vcpkg install sdl2:x64-windows
        ls

    - name: Build OSP-Magnum
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
        cmake --build build --parallel --config Release --target osp-magnum
    
    - name: Prepare Artifact
      run: |
        move build\bin\OSPData build\bin\Release\OSPData
  
    - uses: actions/upload-artifact@v2
      with: 
        name: release
        path: build\bin\Release
